package com.ss.line.shop.core.constants;

public class Constant {
    public static final String RT_EXCHANGE_POINT_DOC_CODE = "PT";
    public static final String RT_EXCHANGE_POINT_DOC_TYPE = "PT";
    public static final String DOC_RUNNING_EMPLOYEE = "EmployeeCode";
    public static final String DOC_RUNNING_EMPLOYEE_PARAM1 = "EM";
    public static final String DOC_RUNNING_SHOP = "ShopCode";
    public static final String DOC_RUNNING_SHOP_PARAM1 = "SP";
    public static final String DOC_RUNNING_FOOD = "FoodCode";
    public static final String DOC_RUNNING_FOOD_PARAM1 = "FD";
    public static final String DOC_RUNNING_DELEVERY_MAN = "DeliveryManCode";
    public static final String DOC_RUNNING_DELEVERY_MAN_PARAM1 = "DM";
    public static final String DOC_RUNNING_CUSTOMER = "CustomerCode";
    public static final String DOC_RUNNING_CUSTOMER_PARAM1 = "CM";
    public static final String DOC_RUNNING_CONGENITAL_DISEASE = "CongenitalDisease";
    public static final String DOC_RUNNING_CONGENITAL_DISEASE_PARAM1 = "CD";
    public static final String DOC_RUNNING_FOOD_STYLE = "FoodStyle";
    public static final String DOC_RUNNING_FOOD_STYLE_PARAM1 = "FS";
    public static final String DOC_RUNNING_KIND_OF_FOOD = "KindOfFood";
    public static final String DOC_RUNNING_KIND_OF_FOOD_PARAM1 = "KF";
    public static final String DOC_RUNNING_MAIN_COMPONENT_TYPE = "MainComponentType";
    public static final String DOC_RUNNING_MAIN_COMPONENT_TYPE_PARAM1 = "MT";
    public static final String DOC_RUNNING_RELIGION = "Religion";
    public static final String DOC_RUNNING_RELIGION_PARAM1 = "RG";
    public static final String DOC_RUNNING_NATIONALITY = "Nationality";
    public static final String DOC_RUNNING_NATIONALITY_PARAM1 = "NT";
    public static final String DOC_RUNNING_SHOP_STYLE = "ShopStyle";
    public static final String DOC_RUNNING_SHOP_STYLE_PARAM1 = "SS";
    public static final String DOC_RUNNING_SHOP_TYPE = "ShopType";
    public static final String DOC_RUNNING_SHOP_TYPE_PARAM1 = "ST";
    public static final String DOC_RUNNING_NEWS_KNOWLEDGE = "NewsKnowledge";
    public static final String DOC_RUNNING_NEWS_KNOWLEDGE_PARAM1 = "NK";
    public static final String DOC_RUNNING_ACCOUNT_TYPE = "AccountType";
    public static final String DOC_RUNNING_ACCOUNT_TYPE_PARAM1 = "AT";
    public static final String DOC_RUNNING_BANK = "Bank";
    public static final String DOC_RUNNING_BANK_PARAM1 = "BK";
    public static final String DOC_RUNNING_USERNAME = "UserName";
    public static final String DOC_RUNNING_USERNAME_PARAM1 = "US";
}
